# -*- coding: utf-8 -*-
"""Manipulasi String

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xjMql_jzb_omWpYOmackm_-CuqoSCP-W
"""





NAMA = 'ALLYSSIA OKTA'
NPM = '2411012016'
PRODI = 'BISNIS DIGITAL'

print (NAMA)
print (NPM)
print (PRODI)

print (NAMA, NPM)

print ('halo saya', NAMA, 'dengan NPM',NPM)

data_lengkap = NAMA + NPM
print (data_lengkap)

data_lengkap_banget = NAMA + NPM + PRODI
print (data_lengkap_banget)

asal_kota = 'bandar lampung'
kodde_pos = 35114

asal_kota_dengan_kode_pos = asal_kota + str (kode_pos)
print (asal_kota_dengan_kode_pos)

asal_kota = "Bandar Lampung"
kode_pos = 35144

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)