# -*- coding: utf-8 -*-
"""éscape Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NgOstx3FVyfVaxG6d-qzi-vJtMAVQstr
"""

print ('Dia berkata : "pergilah!"')

print ("Aku menimpali : \"Apakah kau ingin aku 'angkat kaki'?!\"")

print ("\\(^_^)/ (\\-_-/)")

print ("\\(Ó 3 O)/ (\\^>^)")